-- Insertar categorías
INSERT INTO Categories (name, parent_id, level) VALUES 
('Acordes', NULL, 0),
('Triadas', 1, 1),
('Mayor', 2, 2),
('Menor', 2, 2),
('Aumentada', 2, 2),
('Disminuida', 2, 2),
('Sus4', 2, 2),
('Sus2', 2, 2),
('Tetradas', 1, 1),
('Séptima mayor', 9, 2),
('Séptima menor', 9, 2),
('Séptima de dominante', 9, 2),
('Medio disminuida', 9, 2),
('Disminuida', 9, 2),
('Menor-Mayor', 9, 2),
('Aumentada-Mayor', 9, 2),
('Armonía extendida', 1, 1),
('Acordes de novena', 16, 2),
('Acorde de undécima', 16, 2),
('Acordes de decimotercera', 16, 2),
('Acordes con sexta agregada', 16, 2),
('Acordes sin tercera', 16, 2),
('Acordes cuartales', 16, 2),
('Poliacordes', 16, 2),
('Chord scales', NULL, 0),
('I7 y I6 (jónico)', 26, 1),
('ii7 (dórico)', 26, 1),
('iii7 (frigio)', 26, 1),
('IV7 (lidio)', 26, 1),
('V7 (mixolidio)', 26, 1),
('vi7 (eólico)', 26, 1),
('vii7(b5) (locrio)', 26, 1),
('Funciones armónicas', NULL, 0),
('Tónica', 34, 1),
('Subdominante', 34, 1),
('Dominante', 34, 1),
('Cadencias', NULL, 0),
('Armónicas', 38, 1),
('Conclusivas', 39, 2),
('Semi-conclusivas', 39, 2),
('Desviaciones cadenciales', 39, 2),
('Melódicas', 38, 1),
('Conclusivas', 43, 2),
('Semi-conclusivas', 43, 2),
('No-conclusivas', 43, 2);
